# Generated by Django 5.0.1 on 2024-01-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DScrap', '0002_remove_webpagesnapshot_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagesnapshot',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
