# Generated by Django 5.0.1 on 2024-01-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DScrap', '0003_alter_webpagesnapshot_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='webpagelink',
            name='webpage_snapshot',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DScrap.titlelink')),
            ],
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
        migrations.DeleteModel(
            name='WebpageLink',
        ),
        migrations.DeleteModel(
            name='WebpageSnapshot',
        ),
    ]
