# Generated by Django 5.0.1 on 2024-01-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DScrap', '0004_titlelink_remove_webpagelink_webpage_snapshot_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='titlelink',
            name='image_url',
            field=models.URLField(default=None),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
