# Generated by Django 5.0.1 on 2024-01-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DScrap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpagesnapshot',
            name='link',
        ),
        migrations.RemoveField(
            model_name='webpagesnapshot',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='webpagesnapshot',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.CreateModel(
            name='WebpageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('webpage_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='DScrap.webpagesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='webpage_screenshots/')),
                ('webpage_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='DScrap.webpagelink')),
            ],
        ),
    ]
