# Generated by Django 5.0.1 on 2024-01-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DScrap', '0005_title_titlelink_image_url_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlelink',
            name='relay1',
            field=models.CharField(default='Couldnot Find the relay', max_length=255),
        ),
        migrations.AddField(
            model_name='titlelink',
            name='relay2',
            field=models.CharField(default='Couldnot Find the relay', max_length=255),
        ),
        migrations.AddField(
            model_name='titlelink',
            name='relay3',
            field=models.CharField(default='Couldnot Find the relay', max_length=255),
        ),
    ]
