# Generated by Django 5.0.1 on 2024-01-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DScrap', '0006_titlelink_relay1_titlelink_relay2_titlelink_relay3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
